"""empty message

Revision ID: 59055ff5c287
Revises: 7182ccd562cd
Create Date: 2022-11-08 18:14:43.534719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59055ff5c287'
down_revision = '7182ccd562cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('book', 'id')
    op.add_column('genre', sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('genre', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('genre', 'genre_id')
    op.add_column('book', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('book', 'book_id')
    # ### end Alembic commands ###
